# Generated by Django 6.0.3 on 2026-03-25 12:46

import django.db.models.deletion
import receipts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_number', models.CharField(default=receipts.models.default_receipt_number, max_length=32, unique=True)),
                ('store_name', models.CharField(default='POS Store', max_length=150)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='payments.payment')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='sales.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
