# Generated by Django 6.0.7 on 2026-03-28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(default='default', max_length=32, unique=True)),
                ('store_profile', models.JSONField(blank=True, default=dict)),
                ('appearance', models.JSONField(blank=True, default=dict)),
                ('regional', models.JSONField(blank=True, default=dict)),
                ('pos', models.JSONField(blank=True, default=dict)),
                ('receipt', models.JSONField(blank=True, default=dict)),
                ('payment', models.JSONField(blank=True, default=dict)),
                ('tax', models.JSONField(blank=True, default=dict)),
                ('notifications', models.JSONField(blank=True, default=dict)),
                ('security', models.JSONField(blank=True, default=dict)),
                ('backup', models.JSONField(blank=True, default=dict)),
                ('staff', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
